const lib = require('./lib');

beforeEach(() => { lib._reset(); });

describe('Auto Journal Linking', () => {
  it('should create an auto journal entry with sourceId', () => {
    lib.createAutoJournalEntry('treasury_expense', {
      desc: 'Test expense', amount: 100, date: '2026-01-01',
      ref: 'TR-x1', sourceId: 'x1'
    });
    const entries = lib.STORAGE.get('journalEntries', []);
    expect(entries.length).toBe(1);
    expect(entries[0].autoGenerated).toBe(true);
    expect(entries[0].sourceType).toBe('treasury_expense');
    expect(entries[0].sourceId).toBe('x1');
  });

  it('should not create an entry for unknown type', () => {
    lib.createAutoJournalEntry('unknown_type', { amount: 100 });
    expect(lib.STORAGE.get('journalEntries', []).length).toBe(0);
  });

  it('should remove only the linked auto journal entry', () => {
    lib.createAutoJournalEntry('salary_payment', { amount: 50, sourceId: 's1' });
    lib.createAutoJournalEntry('salary_payment', { amount: 60, sourceId: 's2' });
    expect(lib.STORAGE.get('journalEntries', []).length).toBe(2);
    const removed = lib._removeAutoJournal('salary_payment', 's1');
    expect(removed).toBe(true);
    const entries = lib.STORAGE.get('journalEntries', []);
    expect(entries.length).toBe(1);
    expect(entries[0].sourceId).toBe('s2');
  });

  it('should return false when nothing matches', () => {
    lib.createAutoJournalEntry('salary_payment', { amount: 50, sourceId: 's1' });
    expect(lib._removeAutoJournal('salary_payment', 'nope')).toBe(false);
    expect(lib.STORAGE.get('journalEntries', []).length).toBe(1);
  });

  it('should sync (replace) a linked auto journal entry', () => {
    lib.createAutoJournalEntry('new_expense', { amount: 100, sourceId: 'e1' });
    lib._syncAutoJournal('new_expense', 'e1', { amount: 150, ref: 'EXP-e1' });
    const entries = lib.STORAGE.get('journalEntries', []);
    expect(entries.length).toBe(1);
    expect(entries[0].sourceId).toBe('e1');
    expect(entries[0].ref).toBe('EXP-e1');
    expect(entries[0].lines[0].debit).toBe(150);
  });

  it('should leave manual (non autoGenerated) entries untouched', () => {
    lib.STORAGE.set('journalEntries', [{ id: 'manual1', autoGenerated: false, sourceType: 'new_expense', sourceId: 'e1', lines: [] }]);
    expect(lib._removeAutoJournal('new_expense', 'e1')).toBe(false);
    expect(lib.STORAGE.get('journalEntries', []).length).toBe(1);
  });
});
